networks:
  kafka-practice-network:
    external: true

services:
  order-microservice:
    image: node:22-alpine
    container_name: order-microservice
    ports:
      - '8081:8080'
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:dev
    environment:
      # Application Environment
      - NODE_ENV=development

      # Kafka Configuration
      - KAFKA_BROKER=kafka:9092
      - KAFKA_ORDER_CONSUMER_GROUP_ID=order-consumer-group
      - KAFKA_RETRY_ATTEMPTS=5
      - KAFKA_RETRY_DELAY=3000

      # Service Discovery
      - AUTH_SERVICE_URL=http://auth-microservice:3001
      - API_GATEWAY_URL=http://api-gateway:8080
      - PAYMENT_SERVICE_URL=http://payment-microservice:3003

      # Logging
      - LOG_LEVEL=debug
    networks:
      - kafka-practice-network
    restart: unless-stopped
